[project]
name = "decentralized-affiliate-influencer"
requirements = []
costs_version = 2

[contracts.influencer-affiliate]
path = "contracts/influencer-affiliate.clar"
depends_on = []

[contracts.influencer-staking]
path = "contracts/influencer-staking.clar"
depends_on = ["influencer-affiliate"]

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
