[project]
name = "decentralized-affiliate"
description = "A decentralized affiliate marketing system for influencers"
authors = []
telemetry = false
requirements = []

[contracts.influencer-affiliate]
path = "contracts/influencer-affiliate.clar"
depends_on = []

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
